jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo
    steps:
      - checkout

      - run: npm install
      - run: npm run build
      - run:
          name: test
          command: |
            export APPLITOOLS_BATCH_ID=$CIRCLE_SHA1
            npm test
